### ISSUE TITLE
Shoutouts

### ISSUE THREAD

**Issue by sigvef** [ninjadev/en#26]
in the space scene. Comment here who you want to shout out to!

**Comment by cristeahub** [comment]
mistaaa dooob!

**Comment by stianjensen** [comment]
mrdoob!

**Comment by peterhgombos** [comment]
Solskogen crew!

**Comment by cristeahub** [comment]
- outracks
- trondheimdelegasjonen
- kong harald
- Jan Tolnæs (vaktmester på flateby samfundshus og utleieansvarlig)

**Comment by peterhgombos** [comment]
AbelLan
