### ISSUE TITLE
Gas / lava fountain explosions for doom scene.

### ISSUE THREAD

**Issue by aleksanb** [ninjadev/en#9]
Different effects we will need:
- [x] Gas / flames coming out of cracks.
- [x] Gas geysirs.

Look at https://www.youtube.com/watch?v=rlhefBibcCQ for inspiration.

**Comment by Raane** [comment]
Se også 1:08 her: http://www.youtube.com/watch?v=nMnlxYkZKaU&feature=kp&t=1m08s

**Comment by sigvef** [comment]
for inspiration: http://www.webgl.com/2012/07/webgl-demo-fireball-explosion/
